# Generated by Django 5.0.4 on 2024-05-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_time'),
        ('doctor', '0006_alter_review_unique_together'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'time', 'patient')},
        ),
    ]
