# Generated by Django 5.0.4 on 2024-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, upload_to='patient/image'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
