# Generated by Django 5.0.4 on 2024-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_image_alter_patient_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='patient/image/no-image.jpg', upload_to='patient/image'),
        ),
    ]
