# Generated by Django 5.0.4 on 2024-05-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_designation_doctor_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.designation'),
        ),
    ]
