# Generated by Django 5.0.4 on 2024-05-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_review'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('patient', 'doctor')},
        ),
    ]
