# Generated by Django 5.0.4 on 2024-05-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_review_unique_together'),
        ('patient', '0002_alter_patient_image_alter_patient_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='patient',
            new_name='reviewer',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'doctor')},
        ),
    ]
